### ISSUE TITLE
AsynMultiInterestUserProcessor在执行时被当做SyncUserProcessor

### ISSUE THREAD

**Issue by adisby** [sofastack/sofa-bolt#157]
**Describe the bug**
由于AsynMultiInterestUserProcessor不是AsyncUserProcessor的子类，所以在RpcRequestProcessor.dispatchToUserProcessor()方法中被当做了SyncUserProcessor执行并同步等待，最终抛出异常

![image](https://user-images.githubusercontent.com/1502062/57176263-a25b2280-6e88-11e9-83e7-ba5fd8a1cbc6.png)

https://github.com/alipay/sofa-bolt/blob/531d1c0d872553d92fc55775565b3f7be8661afa/src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestProcessor.java#L222

### Expected behavior
AsynMultiInterestUserProcessor所注册的业务会异步处理
### Actual behavior
AsynMultiInterestUserProcessor所注册的业务被当做SyncUserProcessor并且执行时抛出异常
### Environment

- SOFABolt version: 1.5.3
- JVM version (e.g. `java -version`): 1.8.0_161
- OS version (e.g. `uname -a`): 
- Maven version: 

- IDE version:

**Comment by dbl-x** [comment]
@adisby 能否提供一个复现以上问题的testcase

**Comment by lollapalooza1989** [comment]
I can replay it. 
when I define a UserProcessor class 
public class SimpleAsynMultiInterestUserProcessor extends AsynMultiInterestUserProcessor<RequestBody>

when client call the server,the client side get the error stack:
com.alipay.remoting.rpc.exception.InvokeServerException: Server exception! Please check the server log, the address is 127.0.0.1:8999, id=1, ServerErrorMsg:null
Exception in thread "main" java.lang.AssertionError: RemotingException caught in oneway!
	at com.alipay.remoting.rpc.RpcResponseResolver.preProcess(RpcResponseResolver.java:124) ~[classes/:?]
	at org.junit.Assert.fail(Assert.java:88)
	at com.alipay.remoting.rpc.RpcResponseResolver.resolveResponseObject(RpcResponseResolver.java:54) ~[classes/:?]
	at com.alipay.remoting.demo.RpcClientDemoByMain.main(RpcClientDemoByMain.java:68)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:186) ~[classes/:?]
	at com.alipay.remoting.rpc.RpcClientRemoting.invokeSync(RpcClientRemoting.java:64) ~[classes/:?]
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:143) ~[classes/:?]
	at com.alipay.remoting.rpc.RpcClient.invokeSync(RpcClient.java:198) ~[classes/:?]
	at com.alipay.remoting.demo.RpcClientDemoByMain.main(RpcClientDemoByMain.java:63) [test-classes/:?]
Caused by: com.alipay.remoting.rpc.exception.RpcServerException: [Server]OriginErrorMsg: java.lang.UnsupportedOperationException: SYNC handle request is unsupported in AsynMultiInterestUserProcessor!. AdditionalErrorMsg: SYNC process rpc request failed in RpcRequestProcessor, id=1
	at com.alipay.remoting.rpc.protocol.AsynMultiInterestUserProcessor.handleRequest(AsynMultiInterestUserProcessor.java:38) ~[classes/:?]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:240) ~[classes/:?]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:145) ~[classes/:?]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:366) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_144]

it obviously a bug,I will try to fix it。

**Comment by cytnju** [comment]
@lollapalooza1989 welcome PR to help us fix it.
