### ISSUE TITLE
error: FutureTaskNotCompleted and rpc service not found

### ISSUE THREAD

**Issue by xiaoomai** [sofastack/sofa-bolt#170]
2019-07-02 17:20:39.878 [INFO][Rpc-netty-client-worker-1-thread-4]:com.alipay.sofa.common.log [operationComplete:308] Close the connection to remote address=10.114.4.52:12200, result=true, cause=null
2019-07-02 17:20:39.880 [ERROR][Rpc-netty-client-worker-1-thread-4]:com.alipay.sofa.common.log [getFutureTaskResult:51] Future task has not completed!
com.alipay.remoting.util.FutureTaskNotCompleted: null
	at com.alipay.remoting.util.RunStateRecordedFutureTask.getAfterRun(RunStateRecordedFutureTask.java:48)
	at com.alipay.remoting.util.FutureTaskUtil.getFutureTaskResult(FutureTaskUtil.java:43)
	at com.alipay.remoting.DefaultConnectionManager.getConnectionPool(DefaultConnectionManager.java:563)
	at com.alipay.remoting.DefaultConnectionManager.remove(DefaultConnectionManager.java:331)
	at com.alipay.remoting.DefaultConnectionManager.remove(DefaultConnectionManager.java:318)
	at com.alipay.remoting.rpc.RpcConnectionEventHandler.channelInactive(RpcConnectionEventHandler.java:48)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at com.alipay.remoting.codec.AbstractBatchDecoder.channelInactive(AbstractBatchDecoder.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

the error then like this:
2019-07-02 17:19:49.798 [INFO][Rpc-netty-server-worker-6-thread-6]:com.alipay.sofa.common.log [infoLog:290] Connection channel inactive: 10.114.4.52:53202
2019-07-02 17:19:49.804 [ERROR][http-nio-8080-exec-3]:o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] [log:181] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312: 当前服务[com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade:1.0]的地址[bolt://10.114.5.222:12200?version=1.0&accepts=100000&appName=inst-api-infra&weight=100&language=java&pid=1&interface=com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade&timeout=3000&serialization=hessian2&protocol=bolt&delay=-1&dynamic=true&startTime=1562055551708&id=rpc-cfg-17&uniqueId=&rpcVer=50500,]不可用,或指定的地址不在可用的地址列表中 ] with root cause
com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312: 当前服务[com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade:1.0]的地址[bolt://10.114.5.222:12200?version=1.0&accepts=100000&appName=inst-api-infra&weight=100&language=java&pid=1&interface=com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade&timeout=3000&serialization=hessian2&protocol=bolt&delay=-1&dynamic=true&startTime=1562055551708&id=rpc-cfg-17&uniqueId=&rpcVer=50500,]不可用,或指定的地址不在可用的地址列表中 
	at com.alipay.sofa.rpc.client.AbstractCluster.unavailableProviderException(AbstractCluster.java:433)
	at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:394)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:64)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:285)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)

**Comment by OrezzerO** [comment]
```
2019-07-02 17:20:39.878 [INFO][Rpc-netty-client-worker-1-thread-4]:com.alipay.sofa.common.log [operationComplete:308] Close the connection to remote address=10.114.4.52:12200, result=true, cause=null
2019-07-02 17:20:39.880 [ERROR][Rpc-netty-client-worker-1-thread-4]:com.alipay.sofa.common.log [getFutureTaskResult:51] Future task has not completed!
com.alipay.remoting.util.FutureTaskNotCompleted: null
at com.alipay.remoting.util.RunStateRecordedFutureTask.getAfterRun(RunStateRecordedFutureTask.java:48)
at com.alipay.remoting.util.FutureTaskUtil.getFutureTaskResult(FutureTaskUtil.java:43)
at com.alipay.remoting.DefaultConnectionManager.getConnectionPool(DefaultConnectionManager.java:563)
at com.alipay.remoting.DefaultConnectionManager.remove(DefaultConnectionManager.java:331)
at com.alipay.remoting.DefaultConnectionManager.remove(DefaultConnectionManager.java:318)
at com.alipay.remoting.rpc.RpcConnectionEventHandler.channelInactive(RpcConnectionEventHandler.java:48)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
at com.alipay.remoting.codec.AbstractBatchDecoder.channelInactive(AbstractBatchDecoder.java:342)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.lang.Thread.run(Thread.java:748)

the error then like this:
2019-07-02 17:19:49.798 [INFO][Rpc-netty-server-worker-6-thread-6]:com.alipay.sofa.common.log [infoLog:290] Connection channel inactive: 10.114.4.52:53202
2019-07-02 17:19:49.804 [ERROR][http-nio-8080-exec-3]:o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] [log:181] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312: 当前服务[com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade:1.0]的地址[bolt://10.114.5.222:12200?version=1.0&accepts=100000&appName=inst-api-infra&weight=100&language=java&pid=1&interface=com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade&timeout=3000&serialization=hessian2&protocol=bolt&delay=-1&dynamic=true&startTime=1562055551708&id=rpc-cfg-17&uniqueId=&rpcVer=50500,]不可用,或指定的地址不在可用的地址列表中 ] with root cause
com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02312: 当前服务[com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade:1.0]的地址[bolt://10.114.5.222:12200?version=1.0&accepts=100000&appName=inst-api-infra&weight=100&language=java&pid=1&interface=com.ppdai.inst.infrafacade.service.config.CommonConfigsFacade&timeout=3000&serialization=hessian2&protocol=bolt&delay=-1&dynamic=true&startTime=1562055551708&id=rpc-cfg-17&uniqueId=&rpcVer=50500,]不可用,或指定的地址不在可用的地址列表中
at com.alipay.sofa.rpc.client.AbstractCluster.unavailableProviderException(AbstractCluster.java:433)
at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:394)
at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:64)
at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:285)
at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
```
与 #148  相同, 报错为 Future task has not completed!

**Comment by dbl-x** [comment]
@xiaoomai 按照issue格式描述一下问题，包括提供版本号能必要信息

**Comment by OrezzerO** [comment]
@dbl-x 相关版本信息:
bolt 1.4.6
sofa-rpc-all 5.5.0
java version:: 1.8

还有需要提供的信息吗?

**Comment by dbl-x** [comment]
@OrezzerO 请升级bolt到1.4.8版本。
此问题为异步建连时尝试获取未创建完成的连接时出现的错误，在1.4.8版本中已经将此error调整为warn级别。
