### ISSUE TITLE
Bolt是否支持JDK17 LTS版本?

### ISSUE THREAD

**Issue by liupu9** [sofastack/sofa-bolt#326]
### Your question

Bolt是否支持JDK17 LTS版本?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`): 17
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by chuailiwu** [comment]
如果用其它支持JDK17序列化协议是可以的
当前bolt 使用的默认序列化协议是hession，部分类（如AtomicXXX）会有问题，不过这个在支持中 https://github.com/sofastack/sofa-hessian/pulls

**Comment by liupu9** [comment]
sofa.hessian 目前已经发布了3.5.0 版本. Bolt是不是就已经支持Java17了?

https://github.com/sofastack/sofa-hessian/releases/tag/v3.5.0

**Comment by nobodyiam** [comment]
@Lo1nt is java 17 officially supported?

**Comment by zxuanhong** [comment]
同问，实时hessian已经支持jdk17了的。

**Comment by zxuanhong** [comment]
@chuailiwu @Lo1nt 我在另外一个框架sofa-jraft升级到jdk17。发现集群启动正常，但是他CliService工具会提示Connection is null when do check!。我感觉应该也是这边问题。还是希望尽快升级下jdk。
```
2024-03-07 15:07:43  WARN 92029 --- [flow-demo] [rpc-executor #3] com.alipay.sofa.common.log               : check failed. address: 127.0.0.1:19192, connection: null

com.alipay.remoting.exception.RemotingException: Connection is null when do check!
	at com.alipay.remoting.DefaultConnectionManager.check(DefaultConnectionManager.java:354) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.RpcClient.checkConnection(RpcClient.java:447) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.RpcClient.checkConnection(RpcClient.java:438) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.RpcClient.checkConnection(RpcClient.java:433) ~[bolt-1.6.7.jar:na]
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcClient.checkConnection(BoltRpcClient.java:73) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.isConnected(AbstractClientService.java:81) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.connect(AbstractClientService.java:142) ~[main/:na]
	at com.alipay.sofa.jraft.core.NodeImpl.electSelf(NodeImpl.java:1106) ~[main/:na]
	at com.alipay.sofa.jraft.core.NodeImpl.handleTimeoutNowRequest(NodeImpl.java:3241) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.core.TimeoutNowRequestProcessor.processRequest0(TimeoutNowRequestProcessor.java:52) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.core.TimeoutNowRequestProcessor.processRequest0(TimeoutNowRequestProcessor.java:33) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.core.NodeRequestProcessor.processRequest(NodeRequestProcessor.java:59) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:52) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:34) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer$2.handleRequest(BoltRpcServer.java:124) ~[main/:na]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:235) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:146) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:393) ~[bolt-1.6.7.jar:na]
```

**Comment by chuailiwu** [comment]
hession 已经升级到了3.5.3
另你这个问题应该和jdk17没关系，你可以看下调用栈，只是要要做小目标地址的连接检查，如果没有也不会创建
![image](https://github.com/sofastack/sofa-bolt/assets/2288906/6a188769-0c3f-4bdc-b5bf-daa47a7dc89c)

**Comment by BugTerminat0r** [comment]
> @chuailiwu @Lo1nt 同问，事实hessian已经支持jdk17了的。目前我们是在springboot3.2下使用的。但是由于日志框架需要2.x版本，只发现了使用会出现一下错误 <img alt="image" width="1359" src="https://private-user-images.githubusercontent.com/62740686/309660682-9220a2b3-9d7c-45d1-977e-631b701eff3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODI0ODksIm5iZiI6MTczMDg4MjE4OSwicGF0aCI6Ii82Mjc0MDY4Ni8zMDk2NjA2ODItOTIyMGEyYjMtOWQ3Yy00NWQxLTk3N2UtNjMxYjcwMWVmZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4MzYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODAzNjM1Mzc4MDQxZGIyMGU5ZDYxZjZlZjJiYTM5NTkxZjk1NjFkOGVhZDc0NTNlMTFiZDM2N2FjZDNhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._PXJ8kz6fDEYMR-4WK_B_6YpGP0g62n0n72FQoCo5ek">

你好，我也出现了这个问题了，请问你解决了吗？是springboot版本高的问题导致的吗？你是如何解决的？
